//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheStartUpBuddy
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_USERS
    {
        public int Admin_ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Profile_Photo { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public string Address { get; set; }
        public string Position { get; set; }
    }
}
